/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as SubscribeTokenRouteImport } from './routes/subscribe/$token'
import { Route as ApiV1SubscriptionsRouteImport } from './routes/api/v1/subscriptions'
import { Route as ApiV1SubscriptionsIdRouteImport } from './routes/api/v1/subscriptions/$id'
import { Route as ApiV1SubscriptionsIdTokenRouteImport } from './routes/api/v1/subscriptions/$id/token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribeTokenRoute = SubscribeTokenRouteImport.update({
  id: '/subscribe/$token',
  path: '/subscribe/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SubscriptionsRoute = ApiV1SubscriptionsRouteImport.update({
  id: '/api/v1/subscriptions',
  path: '/api/v1/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1SubscriptionsIdRoute = ApiV1SubscriptionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiV1SubscriptionsRoute,
} as any)
const ApiV1SubscriptionsIdTokenRoute =
  ApiV1SubscriptionsIdTokenRouteImport.update({
    id: '/token',
    path: '/token',
    getParentRoute: () => ApiV1SubscriptionsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/subscribe/$token': typeof SubscribeTokenRoute
  '/api/v1/subscriptions': typeof ApiV1SubscriptionsRouteWithChildren
  '/api/v1/subscriptions/$id': typeof ApiV1SubscriptionsIdRouteWithChildren
  '/api/v1/subscriptions/$id/token': typeof ApiV1SubscriptionsIdTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/subscribe/$token': typeof SubscribeTokenRoute
  '/api/v1/subscriptions': typeof ApiV1SubscriptionsRouteWithChildren
  '/api/v1/subscriptions/$id': typeof ApiV1SubscriptionsIdRouteWithChildren
  '/api/v1/subscriptions/$id/token': typeof ApiV1SubscriptionsIdTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/subscribe/$token': typeof SubscribeTokenRoute
  '/api/v1/subscriptions': typeof ApiV1SubscriptionsRouteWithChildren
  '/api/v1/subscriptions/$id': typeof ApiV1SubscriptionsIdRouteWithChildren
  '/api/v1/subscriptions/$id/token': typeof ApiV1SubscriptionsIdTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subscriptions'
    | '/subscribe/$token'
    | '/api/v1/subscriptions'
    | '/api/v1/subscriptions/$id'
    | '/api/v1/subscriptions/$id/token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subscriptions'
    | '/subscribe/$token'
    | '/api/v1/subscriptions'
    | '/api/v1/subscriptions/$id'
    | '/api/v1/subscriptions/$id/token'
  id:
    | '__root__'
    | '/'
    | '/subscriptions'
    | '/subscribe/$token'
    | '/api/v1/subscriptions'
    | '/api/v1/subscriptions/$id'
    | '/api/v1/subscriptions/$id/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  SubscribeTokenRoute: typeof SubscribeTokenRoute
  ApiV1SubscriptionsRoute: typeof ApiV1SubscriptionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribe/$token': {
      id: '/subscribe/$token'
      path: '/subscribe/$token'
      fullPath: '/subscribe/$token'
      preLoaderRoute: typeof SubscribeTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/subscriptions': {
      id: '/api/v1/subscriptions'
      path: '/api/v1/subscriptions'
      fullPath: '/api/v1/subscriptions'
      preLoaderRoute: typeof ApiV1SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/subscriptions/$id': {
      id: '/api/v1/subscriptions/$id'
      path: '/$id'
      fullPath: '/api/v1/subscriptions/$id'
      preLoaderRoute: typeof ApiV1SubscriptionsIdRouteImport
      parentRoute: typeof ApiV1SubscriptionsRoute
    }
    '/api/v1/subscriptions/$id/token': {
      id: '/api/v1/subscriptions/$id/token'
      path: '/token'
      fullPath: '/api/v1/subscriptions/$id/token'
      preLoaderRoute: typeof ApiV1SubscriptionsIdTokenRouteImport
      parentRoute: typeof ApiV1SubscriptionsIdRoute
    }
  }
}

interface ApiV1SubscriptionsIdRouteChildren {
  ApiV1SubscriptionsIdTokenRoute: typeof ApiV1SubscriptionsIdTokenRoute
}

const ApiV1SubscriptionsIdRouteChildren: ApiV1SubscriptionsIdRouteChildren = {
  ApiV1SubscriptionsIdTokenRoute: ApiV1SubscriptionsIdTokenRoute,
}

const ApiV1SubscriptionsIdRouteWithChildren =
  ApiV1SubscriptionsIdRoute._addFileChildren(ApiV1SubscriptionsIdRouteChildren)

interface ApiV1SubscriptionsRouteChildren {
  ApiV1SubscriptionsIdRoute: typeof ApiV1SubscriptionsIdRouteWithChildren
}

const ApiV1SubscriptionsRouteChildren: ApiV1SubscriptionsRouteChildren = {
  ApiV1SubscriptionsIdRoute: ApiV1SubscriptionsIdRouteWithChildren,
}

const ApiV1SubscriptionsRouteWithChildren =
  ApiV1SubscriptionsRoute._addFileChildren(ApiV1SubscriptionsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  SubscribeTokenRoute: SubscribeTokenRoute,
  ApiV1SubscriptionsRoute: ApiV1SubscriptionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
